services:
  besu:
    image: hyperledger/besu:latest
    container_name: besu-node

    ports:
      - "8545:8545"

    volumes:
      - ./data:/opt/besu/data

    command:
      - --network=dev
      - --data-path=/opt/besu/data
      - --rpc-http-enabled
      - --rpc-http-host=0.0.0.0
      - --rpc-http-api=ETH,NET,WEB3,TXPOOL
      - --host-allowlist=*